version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/helpdesktool
permissions:
   - object: /var/www/html/helpdesktool
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/beforeInstall.sh
      runas: root
   AfterInstall:
    - location: scripts/afterInstall.sh
      runas: root
