version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/helpdesktool
hooks:
   BeforeInstall:
     - location: scripts/beforeInstall.sh
   AfterInstall:
     - location: scripts/afterInstall.sh